[project]
name = "moc-solarpanels"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.122.0",
    "uvicorn>=0.33.0",
]
